'use client';
import { ArrowUpRight, Check, Coins, Leaf, Plus, Settings2, Utensils } from 'lucide-react';
export function BankHeader({goal,onSettings}:{goal:number|null;onSettings?:()=>void}){
 return <header className="bank-header"><div className="wordmark"><span className="app-mark"><Coins size={23}/></span><div><h1>Junk Bank<span className="wordmark-dot">.</span></h1><p>{goal?`${goal} ${goal===1?'occasion':'occasions'} / week`:'A little balance, every day'}</p></div></div><button className="settings-button" aria-label="Open settings" disabled={!onSettings} onClick={onSettings}><Settings2 size={21}/></button></header>
}
export function BalanceCard({balance,rate,busy,onSpend,junkToday=false}:{balance:number;rate:number;busy:boolean;onSpend?:()=>void;junkToday?:boolean}){
 return <section className="balance-card" aria-label="Credit wallet"><div className="balance-eyebrow"><span className="status-dot"/>AVAILABLE CREDITS<ArrowUpRight size={17}/></div><div aria-live="polite" aria-atomic="true" className={'balance-value '+(balance<0?'negative':'')}><span>{balance.toFixed(2)}</span><small>credits</small></div><div className="earn-rate"><Leaf size={14}/><span>+{rate.toFixed(2)} per clean day</span></div><button className="spend-button" disabled={busy} onClick={onSpend}><span><Utensils size={17}/>{junkToday?'Log another occasion':'Spend 1 credit'}</span><Plus size={18}/></button><p className="balance-footnote">{balance<0?'Future clean days will rebuild your balance.':'Your credits stay yours. No expiry.'}</p></section>
}
export function CheckinCard({dateLabel,checked,count,delta,busy,onClean,onJunk,onEdit}:{dateLabel:string;checked:boolean;count:number;delta:number;busy:boolean;onClean?:()=>void;onJunk?:()=>void;onEdit?:()=>void}){
 return <section className="checkin-card"><div className="card-heading"><h2>Today’s check-in</h2><span>{dateLabel}</span></div>{!checked?<><p>What kind of day was it?</p><div className="checkin-actions"><button className="clean-button" disabled={busy} onClick={onClean}><Leaf size={18}/>Clean day</button><button className="junk-button" disabled={busy} onClick={onJunk}><Utensils size={18}/>Ate junk</button></div></>:<div className="checked-state"><span className={'checked-icon '+(count>0?'junk':'')}><Check size={19}/></span><div><strong>{count===0?'Clean day banked':`${count} junk-food ${count===1?'occasion':'occasions'}`}</strong><p>{delta>=0?'+':''}{delta.toFixed(2)} credits {delta>=0?'saved':'used'}</p></div><button className="text-button" onClick={onEdit} disabled={busy}>Edit</button></div>}</section>
}
